services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: tasks
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
